# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: RealStr1ke
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_code: yes
          plugin_code_lines: 12
          plugin_code_load: 100
          plugin_code_visibility: public
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          plugin_habits_days: 14
          plugin_habits_from: 200
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_music: yes
          plugin_music_limit: 4
          plugin_music_playlist: https://open.spotify.com/embed/playlist/1All5I9pyXjJ2ArZt4zuCX
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_projects: yes
          plugin_projects_descriptions: yes
          plugin_projects_limit: 4
#          plugin_repositories: 100
          plugin_repositories: yes
          plugin_repositories_affiliations: owner, contributor 
          plugin_repositories_batch: 100
          plugin_repositories_featured: RealStr1ke/Byte, RealStr1ke/COVID-19
          plugin_repositories_skipped: RealStr1ke, FLVS
          plugin_stars: yes
          plugin_stars_limit: 2
          plugin_topics: yes
          plugin_topics_limit: 20
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          repositories_affiliations: owner, contributor 
          repositories_skipped: RealStr1ke, FLVS
